timwangmusic/Vacation-Planner

main/main.go, planner/planner_API.go
- Refactor server run, simplify code in planner package
- persist username in events table
refactor and improvement
Tested manually locally
=> Refactor server run and persist username in events table

go.mod, go.sum, main/main.go
improve readability and stability of gracefully shut down server with manners package
good industry practice
manually tested
=> Gracefully shut down server with manners pkg

planner/planner_API.go
To facilitate development, skip authentication in development and debug modes.
Use env variable to determine environment.
=> Authenticate on production environment only

go.mod, iowrappers/redis_client.go, iowrappers/users.go, planner/planner_API.go, planner/user_authentication.go, test/redis_client_mocks/geocoding_cache_test.go, test/redis_client_mocks/get_places_geo_cmd_test.go, test/redis_client_mocks/helpers.go, test/redis_client_mocks/maps_last_search_time_test.go, test/redis_client_mocks/nearby_search_test.go, test/redis_client_mocks/users_test.go, user/user.go
Part 3 of removing Mongo dependency by moving user access management to Redis 
- Unit tests are added
- Simplify code for Redis unit-tests
=> Remove mongo dependency

iowrappers/poi_searcher.go, main/main.go, planner/planner_API.go, planner/user_authentication.go
Remove mongo dependency completion
=> Remove mongo dependency completion

go.mod, go.sum, iowrappers/redis_client.go, solution/generate_slot_solution.go, solution/multi_slot_solution.go, test/redis_client_mocks/get_multi_slot_solutions_test.go
currently to solve each request, the solver queries multiple times of Redis sequentially. This is not very efficient considering the distributed system environment in production,
Use go routines to concurrently obtain `slotSolution` results
Added new unit tests and manually tested
=> Optimizations for Solver.Solve

README.md, planner/planner_API.go
update index page path to root
manually tested
=> update index page path

POI/places.go, matching/knapsack.go, matching/knapsack_old_testonly.go, matching/location_matcher.go, matching/places.go, matching/pricing.go, matching/score.go, matching/time_matcher.go, solution/categorization.go, solution/create_slot_solution_candidate.go, solution/timemgr.go, test/knapsack/data/random_gen_visiting_places_for_test.json, test/knapsack/knapsack_test.go, test/redis_client_mocks/get_multi_slot_solutions_test.go, test/score_test.go
Thank you for your contribution to the repo. 
Before submitting this PR, please make sure:
clearly describe changes in your PR, new feature or bug fixes
Describe your code changes in detail for reviewers. Explain the solution and how it fixes the issue case
Were any new tests recorded for this fix, or manually tested
=> Refactor matching.Place struct

graph/time_cluster.go, graph/update_places.go, iowrappers/nearby_search.go, iowrappers/poi_searcher.go, matching/time_matcher.go
Production database and app server data maybe out-synced. For instance, some places are missing the URL field we added at a later time.
Before matching starts, filter and update out-synced places.
=> Update place details

graph/update_places.go, iowrappers/poi_searcher.go, solution/create_slot_solution_candidate.go
follow up to the previous PR
previous PR did not work fully because Google search home URL has been cached
=> update place details for URL being Google search home

graph/time_cluster.go, iowrappers/poi_searcher.go, planner/planner_API.go, templates/plan_layout.html
- Fix map not found in update places method
- Adjust search result view
Fix parameter passing where the argument should be an object instead of a pointer.
=> Fix map not found in update places method

iowrappers/db_operations.go, iowrappers/users.go, planner/planner_API.go, planner/user_authentication.go, test/redis_client_mocks/users_test.go, user/user.go
=> user authentication based on user level

iowrappers/redis_client.go, iowrappers/redis_data_inspections.go, planner/planner_API.go, planner/user_authentication.go
To provide a customized view of production database. Inspect various statistics. 
use various Redis functions to operate on Redis data structures
tested new endpoints against local redis cli results
=> Add database inspection endpoints for Redis stats

iowrappers/data_migrations.go
To reduce multi-thread burden of the migration methods
Previous method does not work properly on production
use an extra parameter `batchSize` to control the maximum number of places to migrate for each call.
report how many places left to migrate so caller know if we still need to call the endpoint
manual integration tests
=> Use batch size to control number of places to update in each migration call

iowrappers/data_migrations.go
=> bug fix in data migrations

iowrappers/data_migrations.go
=> handle detailed search result being null

iowrappers/data_migrations.go, matching/places.go, matching/score.go, test/knapsack/knapsack_test.go, test/score_test.go
Our new score function considers the number of reviews for a place. Implement the new score function.
- Refactor functions in score.go
- Remove average score normalization factor to reduce unexpected factors
Both unit-tests and integration
=> Implement score function with UserRatingsTotal

matching/knapsack.go, matching/knapsack_old_testonly.go, matching/time_matcher.go, test/knapsack/knapsack_test.go
refactor knapsack test, make time and budget limits tighter.
updated unit test
=> refactor knapsack test

iowrappers/maps_client.go, iowrappers/poi_searcher.go, iowrappers/transformers.go, planner/planner_API.go, templates/index.html
Add button to locate user and autofill fields in search page
Users can find things to do in their current location with one click.
JS built-in geolocation functionalities
Manual tests
=> Autofill user location and weekday on index page

POI/time_intervals.go, graph/cluster.go, iowrappers/db_operations.go, iowrappers/geocoding.go, iowrappers/nearby_search.go, iowrappers/poi_searcher.go, iowrappers/redis_client.go, matching/location_matcher.go, planner/planner_API.go, planner/user_authentication.go, utils/csv_io.go, utils/err_handling.go
Redirect user to login page if user uses planning but not logged in.
Performed manual integration tests.
=> Redirect user to login and rename error logging function

templates/common_style.css, templates/plan_layout.html
Use collapse to decorate the planning result page.
Make the planning result page look more clean.
Bootstrap CSS and JS plugin: https://getbootstrap.com/docs/4.3/components/collapse/
=> Feature: Use Bootstrap collapse for the plans page

POI/create_place.go, POI/places.go, iowrappers/nearby_search.go, test/create_visit_location_test.go
Business status is a critical field missing from the `Place` struct. Having this field is essential for filtering out `PermanentlyClosed` establishments.
New feature
Add `status` field to `Place` and getter/setter methods.
=> Add Business Status field to Place struct

templates/index.html, templates/login_page.html, templates/signup_page.html
Most changes are reformatting. Please focus on the real changes.
When users log in, they should see their usernames.
login page passes username to the index page
=> Display username on login success

assets/js/search.js, templates/search_page.html
After users press on the search button, show a spinner showing the server is processing the request.
=> Feature: Show spinner after search request is issued

Dockerfile
Update Dockerfile for the service to launch
Expose port 10000 as usual
=> Update Dockerfile for the service to launch

assets/css/styles.css, assets/js/search.js, assets/js/search_results.js, assets/js/show-trip-details.js, assets/js/user.js, go.mod, iowrappers/photos_client.go, iowrappers/photos_client_test.go, iowrappers/redis_client.go, main.go, planner/planner_APIs.go, solution/planning_solutions.go, solution/solver.go, templates/search_page.html, templates/search_results_layout_template.html, templates/trip_plan_details_template.html
Develop a new endpoint and a new webpage to show trip result details with location photos and other information
N/A
Design doc:
https://docs.google.com/document/d/1E9Od7BLUv_Al4p_dUV4IsakxhxhEG-NZ
- Manual testing on the new endpoint has been performed /plans/:id
- Add unit test cases for the newly added photos_client.go
=> New feature to show trip result details with location photos

assets/js/search_results.js, assets/js/user.js
Save function is broken in search results page
The new modular `updateUsername` method does not return values
=> Fix: username field is undefined in the save plans method

assets/js/search.js, assets/js/search_results.js, assets/js/user.js, iowrappers/redis_client.go, iowrappers/users.go, planner/planner_APIs.go, planner/users.go, templates/profile_page.html, templates/search_page.html, templates/search_results_layout_template.html, templates/trip_plan_details_template.html, test/redis_client_mocks/users_test.go, user/user.go
Create user profile page to display saved travel plans in reverse chronological order.
* Serve the page from backend using Go HTML templates
* Create delete personal travel plan endpoint
Integration tests with Heroku testing app
=> Feature: Create user profile page

iowrappers/redis_client.go, utils/distance.go
Geocoding alias should trim empty location fields
=> Fix: Geocoding alias should trim empty location fields

assets/js/search.js, planner/planner_APIs.go, planner/transformers.go, templates/search_page.html
Implement a basic search autocomplete with jQuery
=> Feature: Basic search autocomplete

go.mod, templates/search_page.html
=> Replace Autofill button in search page with location icon

POI/utils.go, iowrappers/redis_client.go, matching/matcher.go, planner/planner_APIs.go, solution/MDIter.go, solution/planning_solutions.go, solution/solver.go
Backend changes for the pricing feature. Note that the pricing is only on catering locations since Google API does not provide attraction pricing info.
* Added a price range matcher in the matching layer
* Modified cache key for planning solutions
=> Feature: basic places pricing filtering

assets/css/styles.css, assets/js/place.js, assets/js/search_results.js, assets/js/show-trip-details.js, planner/planner_APIs.go, solution/solver.go, templates/search_results_layout_template.html, templates/trip_plan_details_template.html
Add user plan saving feature on the plan show page. 
N/A
- Reuse existing backend logics to handle plan saving POST request. 
- Refactor some common JS data structures (View, Place) from search_results.js
- Add frontend JS logics in plan show page to trigger and send a plan saving request 
- Pass existing unit tests
- Manually tested both plan saving features
=> Save plan on plan show page

POI/places.go, POI/time_intervals.go, assets/js/plan_template.js, assets/js/search.js, assets/js/user.js, assets/js/utils.js, iowrappers/nearby_search.go, iowrappers/poi_searcher.go, iowrappers/redis_client.go, matching/time.go, planner/planner_APIs.go, solution/solver.go, templates/plan_template.html, templates/search_page.html, test/redis_client_mocks/cached_planning_solutions_test.go
Provide a mechanism for users to customize plans at a refined level
Towards our mission of providing more user customizations.
=> [Feature]Planning customization

assets/css/styles.css, templates/search_page.html
Front end addition for the price selection feature
=> [Price][Front End]Add select form option for price

assets/js/plan_template.js, iowrappers/redis_client.go, templates/plan_template.html
=> Fix: Display error message if no valid plan can be found

templates/search_page.html
Since the `About` links to the GitHub repository, we are using the GitHub-alt Font awesome icon for that. it looks cleaner 
=> [Task] add GitHub icon

assets/js/plan_template.js, planner/planner_APIs.go, planner/utils.go, templates/plan_template.html
Align look and feel of plan customization result tables with those in the search results page
=> Adjust styles of plan customization result tables 

assets/css/styles.css, assets/js/__mock__/maps.js, assets/js/google_map.js, assets/js/google_map.test.js, assets/js/show-trip-details.js, assets/js/show-trip-script.js, package-lock.json, package.json, planner/planner_APIs.go, templates/trip_plan_details_template.html
- Add an embedded Google Map object in plan show page
- Add markers based on trip places locations (lattitude, longitude) and place category (visit or eatory)
N/A
- Add place locations (lat, lng) into the response of getPlanDetails request
- Follow Google Map API example and create a separate JS file "google_map.js" 
- Inside the JS file, initialize the map with markers for different places
- Note: some functions/codes are moved from "show-trip-details.js" into a separate script "show-trip-script.js"
Did you add any new …
=> Embed Google Map to show plan locations

iowrappers/redis_data_inspections.go, planner/planner_APIs.go
Reduce backend calls to get city list when user types in the location
Load city list when server starts
=> Preload city list when server starts

templates/login_page.html, templates/signup_page.html
=> Upgrade log-in and sign-up pages to use Bootstrap 5

go.mod, go.sum, iowrappers/users.go, templates/login_page.html, templates/signup_page.html, test/redis_client_mocks/users_test.go
* Allows users to log in with username or email address
* Use Bootstrap toasts to replace plain JS alert when duplicated usernames are detected
* Enhance Redis backend: created 2 hashes for mapping emails and usernames to user IDs
=> Improve user authentications

go.mod, go.sum, iowrappers/users.go, main.go, planner/planner_APIs.go, planner/users.go, templates/login_page.html, test/redis_client_mocks/users_test.go, user/user.go
* Basic Google OAuath2 implementation
* Users can use their Gmail email addresses to login
* Depend on Golang OAuth package
* Users are still required to sign up in the sign-up page. If the user email is not signed up, they shall be redirected to the login page
=> Feature: User log in with Google OAuth2

.github/workflows/go.yml, go.mod, iowrappers/data_migrations_test.go, iowrappers/maps_client.go, iowrappers/transformers.go, main.go, matching/knapsack_v1_test_only.go, planner/planner_APIs.go, planner/redis_streams_logging.go, solution/solver.go, test/insert_interval_test.go, test/knapsack/knapsack_test.go
=> Update go.yml to include linter

iowrappers/redis_client.go, matching/knapsack.go, matching/knapsack_v1_test_only.go, matching/score.go, planner/planner_APIs.go, solution/planning_solutions.go, solution/solver.go, test/score_test.go
Update the plan score function for efforts to improve plan generation quality. Its [design doc](https://docs.google.com/document/d/1XNIJ9nKIoW6SnmV3AV4vzgy2vbR7fiVA2ywqXhVZ02w/edit) is shared.
Current plan score function can favor long travel distance in certain scenarios, details are disclosed in the [design doc](https://docs.google.com/document/d/1XNIJ9nKIoW6SnmV3AV4vzgy2vbR7fiVA2ywqXhVZ02w/edit)
Use a constant distance normalization factor (e.g. search radius). In the future, we plan to allow user to adjust this …
=> Improve Travel Plan Score Calculation

assets/js/plan_template.js, planner/planner_APIs.go, templates/plan_template.html
* Autofill start time when adding new rows
* Add location autofill button
* Add price range selection dropdown
=> Improve plan template

assets/js/search_results.js, planner/planner_APIs.go, templates/search_results_layout_template.html, utils/json_framework.go
Add a button to scroll smoothly to the top on search result page.
Basic JS is sufficient.
=> Add scroll to top on search results page

assets/js/profile.js, assets/js/search.js, assets/js/search_results.js, assets/js/user.js, iowrappers/mailer.go, planner/planner_APIs.go, planner/users.go, templates/profile_page.html
* Moves profile page endpoint path to v1/profile for better organization.
* Moves script section of profile page to separate JS file to use as a module.
*
=> [Refactor] Profile page

assets/js/search.js, templates/search_page.html
Show search spinner when users press the search submit button
* Previously we only show the search spinner when users press enter inside the search location box
* Now we also show search spinner when users press the search button
A screenshot of the search spinner indicator
=> Show spinner in the location box when the search button is pressed

POI/places.go, POI/time_intervals.go, iowrappers/data_migrations.go, iowrappers/redis_client.go, iowrappers/redis_data_inspections.go, iowrappers/reverse_index.go, iowrappers/users.go, matching/match_cluster_centers.go, test/redis_client_mocks/reverse_index_test.go
Kick start the effort to improve solution generation speed using Reverse Index.
* The first commit in this PR shortens RedisClient receiver names per Go readability recommendations.
* Define reverse index and its metadata.
* Define methods to save/retrieve indexes with Redis sorted set.
=> Reverse index creation and retrieval

assets/js/search_results.js, assets/js/utils.js
When user auto completes the location with search input, the resulted string in search result page URL does not follow traditional formatting for city, country names, etc.
Fix the format while posting the plan to be saved to the backend.
=> Fix: user saved plan location format

assets/js/plan_template.js, templates/plan_template.html
Pagination on plan template page.
* Use the simple pagination plugin.
* The number of plans and number of items parameters are tentative and subject to change.
=> Feature: Pagination on plan template page

iowrappers/redis_client.go
Previously the Redis client implementation of `nearbySearch` does not consider if the number of results satisfy minimum requested.
* Dynamically expand search radius to find the minimum number of places
=> Dynamically expand search radius for Redis

assets/js/user_profile.js
Add fixed CSS style max width to user favorite card, and align it with user's saved plans
=> Improve the UI of user favorite in user profile page

iowrappers/nearby_search.go
=> Chore: Simplify error handling in extensiveNearbySearch function

assets/js/forgot-password.js, assets/js/login.js, assets/js/reset-password.js, assets/js/utils.js, iowrappers/mailer.go, iowrappers/users.go, iowrappers/utils.go, planner/planner.go, planner/users.go, templates/forgot_password_page.html, templates/login_page.html, templates/reset_password_page.html, test/redis_client_mocks/users_test.go, user/user.go
The user password reset process is as follows:
* User clicks on “forgot password” on login page
* Redirect them to recover password page to enter emails
* Backend sends an email for resetting password
* User clicks on the included link and fill out a form with new password
* Add forgot password page and reset password page
* Enhance mailer to send password reset emails
=> Reset user password

POI/categories.go, iowrappers/nearby_search.go, iowrappers/redis_client.go, matching/matcher.go, planner/solver.go, test/redis_client_mocks/nearby_search_test.go
We used to have problems in finding enough number of pricy restaurants when we increase the price level selection in the main search page. In this PR, we try to improve the search for more expensive restaurants (PriceLevel >= 3). 
There are mainly two changes
- we increase the search radius by 4 times to find more expensive restaurants in external map search with Google API, we add price level filtering condition in the map search request to counteract the potential increase of irrelevant API calls. 
- we encode eatery price level info into redis nearby search key, so that results are also grouped by their price levels in redis nearby search. This can enable potential increase of search radius later.
search location is "new york, ny, usa", date is "03-12-2023", the price level is $$$ …
=> Improve searching for expensive restaurants

POI/categories.go, iowrappers/nearby_search.go, iowrappers/redis_client.go
Use pipeline to make sure the two operations are checked in before queries come in. This makes sure that results are consistent.
=> Refactor: execute saving place ID to sorted list and place itself in a single pipeline execution

POI/categories.go, README.md, assets/js/forgot-password.js, assets/js/jwt-decode.js, assets/js/plan_template.js, assets/js/reset-password.js, assets/js/search.js, iowrappers/nearby_search.go, iowrappers/photos_client.go, iowrappers/photos_client_test.go, iowrappers/transformers.go, matching/score.go, planner/users.go, templates/search_results_layout_template.html
Thanks GoLand problem detector!
Miscellaneous fixes for the sloppiness in code base.
=> Chore: miscellaneous fixes

go.mod, go.sum, planner/planner.go, planner/solver.go, planner/transformers.go, test/optimal_plan_test.go
We can model the planning problem in a Bipartite graph where the edges connect two sets with a set of time slots and a set of places. Then the problem reduces to find a maximum matching in the graph. The weights of the edges are scores of the places. We can use a Hungarian Algorithm solver to solve the maximization problem.
* Compute a weight matrix for the Bipartite graph.
* Fix weight so we can solve a variation of the minimization problem which the Hungarian Algorithm designed to solve.
* Return place IDs as the solution.
* Example request: `{
"location": {
"city": "Shanghai",
"country": "China"
},
"slots": [
{
"time_slot": {
"slot": {
"start": 10,
"end": 12
}
},
"category": "Visit"
},
{
"time_slot": {
"slot": {
"start": 14,
"end": 16
}
},
"category": "Visit"
}
],
"radius": 10000, …
=> Feat: solve optimal planning problem with Hungarian Algorithm

.github/workflows/go.yml, go.mod, iowrappers/data_migrations.go, utils/math.go
upgrade Go version to 1.21 so we can use those cool new features. Also remove unused functions in utils package.
=> Chore: upgrade Go version to 1.21

POI/places.go, POI/time_intervals.go, iowrappers/redis_client.go, planner/solver.go, planner/transformers.go, test/redis_client_mocks/cached_planning_solutions_test.go
* [Design Doc](https://docs.google.com/document/d/15JFauy-u5L1GitJLLJWjU2MhtrzvQfP2K7Gqvpj-FeA/edit?usp=sharing)
=> [Feature] Implement a new travel plan persistence index

iowrappers/nearby_search.go, matching/time.go, planner/solver.go
Improve the nearby search with Google Maps logging
* Calculate number of places obtained per iteration per `PlaceType`.
* Remove place details logging for reducing logging noise.
=> Enhance: nearby search logging

main.go
Previously a `os.Signal` channel blocks the main go routine and the `sync.Wait` is basically useless.
* Dispatch event workers in the main go routine.
* Spin a go routine when receiving shutdown signals from OS. Close the event channel when shutdown signal is received.
* After workers are done the main go routine can continue.
* Finally we gracefully close the server so that no more requests can be sent.
=> Refactor: spin a go routine to close channels before server shut down

planner/planner.go
Recently we added a guardrail against plan generator iterator having to process place clusters with zero place. However the error returned by the place cluster generator was not handled properly, leading to not redirecting to the root path.
* Redirect to `/v1` when internal error happen.
=> Fix: blank page when no solution is found

package-lock.json, package.json
Adjust package name to conform to npm package pattern.
* run `npm install` to update package-lock.json file.
=> Chore: update package-lock.json

README.md, docker-compose.yaml
Update run with docker compose section in README.
=> Documentation: Update run with docker compose section in README

matching/matcher.go, planner/solver.go, planner/solver_test.go
=> Refactor: Place matching use strategy pattern

assets/js/login.js, assets/templates/login_page.html, iowrappers/users.go, planner/users.go, test/redis_client_mocks/users_test.go
Previously users cannot login with their emails, even though the input element suggest they can do so. This was caused by backend not properly handling logging in with emails.
* Disallow user logging in with usernames and prefer logging in with emails only.
* Update log-in form icons.
* Reformat some related HTML and JS files.
=> Fix: Enforce user login with email

iowrappers/photos_client.go
=> Chore: reformat photos_client.go

assets/css/styles.css, assets/templates/login_page.html
Ref: SO https://stackoverflow.com/a/76013019
Relying on a remote Wikipedia SVG is not stable, especially when remote server is under maintenance.
* Code referenced from stackoverflow [question](https://stackoverflow.com/a/76013019) 
* Reformat the CSS file with Prettier
=> Fix: Use local SVG as Google login icon

assets/js/plan_template.js, assets/js/search.js, assets/js/search_results.js, assets/js/show-trip-details.js
Having username does not achieve anything since the backend relies on cookies to identify users. So it is cleaner and less confusing to users for not including the username parameter in user profile requests.
* The other changes are formatting with Prettier.
=> Remove username parameter in user profile requests

assets/templates/trip_plan_details_template.html
Remove API key and disable Maps feature in details page.
* The API key has been deleted.
=> Remove API key and disable Maps feature in details page

assets/js/google_map.js, assets/templates/trip_plan_details_template.html, planner/planner.go
* Fix Maps async loading error
* Adjust zoom to city level
=> Re-enable Mini Google Maps feature in plan details page

assets/js/search_results.js, iowrappers/users.go, planner/planner.go, planner/users.go
Address unwanted changes from #356.
=> Cleanup user plan saving update related changes

iowrappers/redis_client.go
The Go test tool detected that having concurrent access to the known_cities_name_to_id redis map results in race condition. Instead of using transactions which will not provide better performance than sequential executions, this change removes concurrency pattern all together for this function.
* Remove concurrency pattern from the `AddCities` method.
- `Go test --race` shows that the race condition is gone after the change.
=> Fix: race condition for AddCities method

assets/js/user_profile.js, planner/planner.go, planner/users.go
The app lacks some key security configurations that makes it prone to common security attack schemes.
* Add a few security headers such as XSS protections
* Enhance cookie security settings
* Remove username from user saved plan details page URL to information leakages.
=> Security Enhancements

go.mod, go.sum, planner/planner.go
Set up router rate limiter with a middleware.
* Limit requests per IP per hour to 100. We can make this configurable later.
=> Set up router rate limiter

assets/templates/search_page.html
Discord invite has expired, so update with new link
=> update discord invite

assets/js/google_map.js, assets/templates/trip_plan_details_template.html
=> Feat: Add route to mini map

POI/places.go, iowrappers/data_migrations.go, iowrappers/nearby_search.go, planner/planner.go
Factor out the details search and leave a place holder for reducing number of details search calls.
* Reduce the `ExtensiveNearbySearch` function size by factoring out the details search function
* Add `lastUpdatedAt` timestamp for `POI.Place` type
~~-[ ] Added new unit tests~~
=> Refactor: nearby search with maps
