timwangmusic/Vacation-Planner

- templates/plan_layout.html
Styling planning result page with flex-box. This is basically a sync-up with production.
Use CSS flex box for centralized card-like layout
> Styling planning result page with flex-box

- iowrappers/redis_client.go
- planner/redis_streams_logging.go
- Remove the code that stores API usage events in Mongo
- Workers update Redis with API statistics
Part 2 of removing Mongo dependency
> Store basic API statistics in Redis

- graph/update_places.go
- iowrappers/geocoding.go
- iowrappers/maps_client.go
- iowrappers/nearby_search.go
- iowrappers/poi_searcher.go
- iowrappers/redis_client.go
- planner/planner_API.go
- solution/multi_slot_solution.go
- test/redis_client_mocks/geocoding_cache_test.go
- test/redis_client_mocks/get_places_geo_cmd_test.go
- test/redis_client_mocks/helpers.go
- test/redis_client_mocks/nearby_search_test.go
Io-wrappers package has 2 important types, `MapsClient` and `RedisClient`, responsible for external communications between our server and external API / Redis server. And their core functionalities of providing geo-location based searching functions are quite similar. Thus it makes sense to refactor and consolidate both under an interface `SearchClient`.
Re-define the `SearchClient` interface
Refactor factory methods for `MapsClient` and `RedisClient`
Refactor some `MapsClient` methods to none-type dependent functions
manually tested
> Refactor maps/Redis client to implement an interface

- graph/time_cluster.go
- graph/update_places.go
- iowrappers/maps_client.go
- iowrappers/nearby_search.go
- iowrappers/poi_searcher.go
- iowrappers/redis_client.go
- test/redis_client_mocks/nearby_search_test.go
- test/update_places_details_test.go
For the places without URL after update places with new detailed search, Redis is not updating. 
Production server makes way too many place details search calls
- Make `updatePlacesDetails` method returns a list of places and update Redis. 
- Fixed issues in the Redis update method.
Integration test procedure
- Obtain places without URL by removing URL field in the field mask
- Remove slot solutions to force the call flow to the lower-level place search
- Since search timer is not up, it forces the call flow to call the `updatePlaceDetails` function
- Check if the same place get updated URL
> Fix Redis place update issue

- graph/update_places.go
- iowrappers/nearby_search.go
- iowrappers/poi_searcher.go
- utils/err_handling.go
Added more log to debug maps: NOT_FOUND error
Newly implemented updateplacedetails function does not work well under designed scenarios.
More log entries are added. Changed printstack threshold. No logic change is made to make the bug repeatable.
> [test] added logs and changed traceback print shreshold

- templates/plan_layout.html
One-day plan page layout was broken on mobile. Root cause is column width is not adjusting per device type.
Use Boostrap's auto-column layout feature we can specify how many columns we want for each row. Then let Bootstrap's magic fix the breakpoints per device type.
Tested on Heroku preview app and mobile.
> Simplify plan layout css

- .github/workflows/go.yml
- Procfile
- config/config.yml
- go.mod
- iowrappers/maps_client.go
- main.go
- planner/planner_API.go
- solution/multi_slot_solution.go
As a first step for developing data migration endpoint, we need a tiny database for available fields from Google Maps details search. Use config file to convey this information.
Define config structure in `config.yml` and load the data with `gopkg.in/yaml` package.
performed manual integration tests
> Get Google Maps detail search fields from config file

- planner/planner_API.go
- templates/login_page.html
- templates/search_page.html
Currently after logged-in user goes to search page, the username is lost. This is confusing since users would not know if they logged in or not.
Previous implementation has flaws. Cookies are only available on /v1 path endpoints.
- Redirect home page request to /v1
- Search page verifies JWT token and use username from cookies to render
- Added JS-cookie library can be used for logging out users as well
- [ x] You have added unit tests
> Fix: Search page receives cookies and verifies them

- assets/js/search.js
Discover that the main search page is missing date display after clicking autofill button.
The date value needs comply with the format yyyy-mm-dd for the date input. For certain dates such as 10/01/2021, the day value can be a single digit (1) which violates the requirement.
Prepend a "0" to day, if day is less than 10.
Manual integration tests locally for functionalities including autofill, trip result searching etc.
> Bug fix of missing date display in search page after clicking autofill

- assets/js/jwt-decode.js
- assets/js/search.js
- iowrappers/maps_client.go
- planner/planner_API.go
- planner/user_authentication.go
- solution/solver.go
- templates/search_page.html
Previously, after users logged in, the backend server assigns both JWT and a username to the session cookies. The username cookie is redundant and confusing to the front-end as well as backend functions. In this change, we attempt to remove the username from the cookie assignments and extract the username from the JWT claims.
* Use `jwt-decode` module to extract claims on the front-end
* Simplify backend user authentication methods
> Fix: Set only JWT in session cookies

- assets/js/search_results.js
- templates/search_results_layout_template.html
Allows users to click the edit button and make changes to a travel plan and save the resulting plan to their profile. Disable edit button after save.
* Add an Edit button for each plan to trigger table editing
* Use jQuery to read table before save
> Feature: Basic travel plan editing

- assets/js/search.js
- iowrappers/maps_client.go
- iowrappers/nearby_search.go
- iowrappers/poi_searcher.go
- iowrappers/redis_client.go
- iowrappers/transformers.go
- planner/planner_APIs.go
- solution/solver.go
- templates/search_page.html
- test/redis_client_mocks/geocoding_cache_test.go
When searching cities with same name, the planner always uses the most popular city. This is not ideal especially when using Autofill.
Location handling mechanisms lacking `Administration area level one` info.
Add `Administration area level one` info and allow users to enter either `City, Country` or `City, Region, Country` in the search bar.
> Fix: Add administration area level one to user input location

- templates/profile_page.html
- templates/trip_plan_details_template.html
Fix issue #205 
The "Back" link on the trip result page works in laptop browser and Android phones but NOT on iphones. 
Not sure, seems to os-related compatibility.. 
Follow the suggested solution in one stack overflow post. Use inline javascript to directly update href attribute of the link.
https://stackoverflow.com/questions/8814472/how-to-make-an-html-back-link
No new tests. Pass all existing tests.
> Fix issue of broken back button in mobile browsers

- iowrappers/data_migrations.go
- iowrappers/data_migrations_test.go
- iowrappers/maps_client.go
- iowrappers/redis_client.go
- iowrappers/utils.go
- planner/planner_APIs.go
We noticed that a significant number of places data in production have incomplete fields, resulting in plans missing URLs or photo references. This deficiency is breaking our features such as trip details.
When adding new fields such as photos, older places data become stale. Furthermore, some original data from Google lack those fields.
* Remove places without URL or photo reference in database.
* Only admins can trigger the data migration.
> Data migration: remove places without URL or photo reference in database

- solution/planning_solutions.go
Fix issue #203
Somehow `placeIds` is just a reference of `travelPlan.PlaceIDs` in the `TravelPlansDeduplication` function, so `radix.Sort(placeIds)` also unexpectedly alters the sequence of Place IDs in travel plan.
Make a new copy of `travelPlan.PlaceIDs`
Pass existing unit tests
> Fix incorrect sequence of PlaceIds in travel plan stored in Redis

- POI/places.go
- matching/models.go
- matching/places.go
- matching/pricing.go
- matching/score.go
- matching/transformers.go
- test/create_visit_location_test.go
- test/redis_client_mocks/nearby_search_test.go
- test/score_test.go
Google Maps API provides price level from 0 to 4, previously the model is coupled with the range from the API. This change  attempts to reduce the coupling and ease further feature development.
> Refactor: Add type to price level

- POI/places.go
- iowrappers/nearby_search.go
- iowrappers/poi_searcher.go
- iowrappers/redis_client.go
- iowrappers/utils.go
- matching/matcher.go
- templates/search_page.html
- test/redis_client_mocks/nearby_search_test.go
Due to recent events such as COVID-19, many business are affected. As such place data from Google Maps tend to change relatively more frequently. Therefore it is important we filter out business that are temporarily closed or permanently closed.
Planning results contain temporarily closed or permanently closed places.
Filter non-operational places in the search client.
> [Enhancement]Filter places business status operational

- assets/js/search.js
The progress spinner was visible if we went back to the search page via hitting the back button on the browser. 
The spinner should be invisible in this case.
Spinner DOM property was cached in the browser, and when the browser traverse back in history. The "visible" state is used for the spinner DOM.
Add a new HTML event listener to hide the spinner whenever there is visibility change of the page.
Manually tested with both fast loading …
> Fix the issue of seeing spinner when going back to the search page

- graph/vertex.go
- solution/planning_solutions.go
- test/solution_candidate_selection_test.go
Previously the solver first compute all the planning solutions before sorting them by score with the priority queue. This creates a huge memory overhead when the number of requested categories is large (>4). We have seen multiple occurrences of out of memory error in production.
The solver memorize all the solutions and then feed the list to ranker.
Generate planning solutions and feed new solutions to ranker **at the same time**.
Note that the usage of `TravelPlansDeduplication` function is removed, there is currently no good solution to deduplicate permutation travel plans without incurring large memory footprints.
Did you add any new test for this change, performed manual integration tests, or both? <-- Both
> Fix: Out of memory while generating planning solutions

- assets/css/styles.css
- assets/js/search.js
- assets/js/utils.js
- iowrappers/maps_client.go
- iowrappers/nearby_search.go
- iowrappers/poi_searcher.go
- iowrappers/redis_client.go
- iowrappers/transformers.go
- matching/matcher.go
- planner/planner_APIs.go
- planner/utils.go
- solution/planning_solutions.go
- solution/solver.go
- templates/login_page.html
- templates/search_page.html
For metropolitan areas, using the current location often resolves to the downtown areas. We provide an option for users to use their exact current location for searching nearby places.
Add a button in the search page for this new option.
The trickier part for the backend change is how to use cache properly. Redis is using lat/long for searching places. Therefore we need to feed the Redis client with precise location. At the same time, we need to maintain data freshness, therefore we need to reverse geocoding in order to find the city-level info in order to determine when to perform a new search.
> Feature: use precise location for travel planning

- iowrappers/maps_client.go
- iowrappers/users.go
The authentication system do not treat user emails case-insensitive.
* Save email addresses in lower case when users create accounts
* Check lower case converted email addresses when authenticating users.
Expected behaviors:
* When users log in with usernames, differentiate cases.
* When users log in with emails, do NOT differentiate cases.
* When users sign up they cannot use emails of same lower-cased form.
> Fix: Insensitive to user email for login and signup

- assets/js/search.js
- templates/search_page.html
Also restore log-out function on the search page.
Setting location on change does not guarantee consistent location persistence behavior.
* Set location in `SessionStorage` only when the form is submitted.
* Restore log out functionality.
> Fix: persist location input value when going back to the search page

- solution/planning_solutions.go
- test/solution_candidate_selection_test.go
Bug was found when examining scores of top plans, and the current top plans are shown in a reverse order their plan scores. 
The bug is due to the usage of min-heap. The result list is in ascending order instead of descending order. A simple fix is to reverse the output plan list.
> [Fix] Correct the order of top plans returned from search

- iowrappers/redis_client.go
- solution/solver.go
Use precise location feature does not behave consistently. Only fresh searches return correct results. Some debugging work shows that the issue lies in Redis plan search uses city, country location, which is not available when using precise location feature.
* Make sure to perform reverse geocoding before sending request to Redis
> Fix: Redis plan search does not work with precise location

- assets/js/plan_template.js
- go.mod
- go.sum
- iowrappers/redis_client.go
- planner/planner.go
- planner/solver.go
- planner/transformers.go
- planner/utils.go
- templates/plan_template.html
- test/redis_client_mocks/cached_planning_solutions_test.go
- test/solution_candidate_selection_test.go
We often see critical errors from deployed service that requests are timing out for more than 30 seconds. For large scale computations, currently we cannot generate a solution due to the complexity. The requests should not be blocked and should be timed out within reasonable time.
* Use `context.WithTimeout` to limit `GenerateSolutions` run time.
* Use `timeout` Gin middleware to limit regular request run time.
> Refactor: Plan generation timeout

- iowrappers/users.go
- planner/planner.go
- planner/users.go
After PR# checked in, existing users cannot login to their accounts.
* Create an empty favorites field in user views for existing users.
* Enforce user credential for non-prod environments.
> Fix: broken user log in functionalities

- assets/js/plan_template.js
The frontend request times out and no banner is shown to users. This is due to frontend request timeout before backend does.
* Show the `Search request is too powerful, please try to reduce the number of time slots requested.` banner when frontend Axios request times out.
> Fix: displays timeout banner when Axios request times out

- planner/solver.go
- test/solution_candidate_selection_test.go
The `FindBestPlanningSolutions` method used to return `[]PlanningSolution`. The issue is when time out happens, the iterator's loop has to terminate and no meaningful result will be returned.
* Refactor `FindBestPlanningSolutions` method to return `chan PlanningResp`.
* Refactor calling function code.
* Set context with timeout in `FindBestPlanningSolutions` parent function.
> Refactor: use channel for FindBestPlanningSolutions function response

- iowrappers/transformers.go
- iowrappers/users.go
- planner/users.go
- user/user.go
Persist user last login timestamp, this helps tracking user engagement with the website.
* Add a new field in user `view` and update DB when user logs in.
* Remove unused structs.
> Feature: persist user last login timestamp

- planner/planner.go
- planner/solver.go
- planner/streaming.go
- planner/users.go
* Shorten receiver names per golang idioms.
* Use `ctx` as a standard name for context variable names.
> Chore: rename all context names to ctx and planner receiver names to p in Planner package

- planner/MDIter.go
- planner/solver.go
- test/solution_candidate_selection_test.go
Discover that our plan solver can miss the last point in the multi-dim iterator algorithm. It was found in the associated unit test, where the top return plan is supposed to have a score of 99 instead of 98. 
Swap the sequence of iter.Next() and createPlanningSolutionCandidate(iter,) methods
Initialize the starting status in multi-dim iterator as [0, 0, -1] instead of [0, 0, 0].
> Bug Fix: fix the bug where plan solver misses the last point in multi-dimensional search

- iowrappers/users.go
- planner/users.go
Logins via OAuth do not show usernames.
Because of the difficulty in setting up oauth in staging and test, we have to bump up logging levels to test in prod, which is bad practice.
> FIx: logins via oauth do not show usernames

- assets/js/search.js
- planner/planner.go
- templates/search_page.html
Show alert banner when no travel plan is found for searches on home page. Previously we are showing user 2 lines of strings, which is confusing and rudimentary.
* Achieving this is tricky due to our backend rendering for standard plan results page
* Use redirect and detect this with `document.referrer` and path difference checks
> Enhancement: show alert when no travel plan is found

- assets/js/search.js
The newly added alert message when no plan is not found persist when users swipe backward on phones or reload the page.
* This change fixes the issue by making sure the navigation is of `navigate` type instead of the other types described [here](https://developer.mozilla.org/en-US/docs/Web/API/PerformanceNavigationTiming/type).
> Fix: persistent alert message when back forward or reload the page

- assets/js/user_profile.js
Add a button to direct users to plan details page for their saved plans.
* Use `original_plan_id` field in plan views to construct URL.
> Feat: show plan details button on user profile page

- assets/js/forgot-password.js
- assets/js/reset-password.js
- iowrappers/users.go
- planner/planner.go
- templates/reset_password_page.html
- user/user.go
In the previous PR, we already created a verification code for each password reset request. But we did not make proper use of it. Also users should not need old password to set new ones, otherwise why would they need to reset?
* Verify user email against verification code to make sure URL is not tampered.
* Verify password reset code is claimed only once.
* Removed requirement for user entering old password.
> Verify password reset requests with code

- assets/js/search.js
- planner/planner.go
When users are navigated back to the search page, they will still see the location input unchanged since we persist this in session storage. However when users attempt to search again without changing the input, they will see the error message `location format must be city, region, country or city, country`. This is cause by `precise-location-flag` being reset to `false` upon loading the page.
* Persist `precise-location-flag` value in session storage
* Load the persisted value upon page loading
* Reset `precise-location-flag` value when user intentionally changes input
> Fix: precise location flag resets when user is navigated

- go.mod
- go.sum
- iowrappers/cities.go
- iowrappers/poi_searcher.go
- iowrappers/redis_client.go
- iowrappers/transformers.go
- planner/planner.go
- test/redis_client_mocks/nearby_cities_search_test.go
In this change, we integrate a new service provider: [Geonames web provider](https://www.geonames.org/export/web-services.html) through a customized client. The services provide look ups for nearby cities given a location. This helps when our service recommends nearby cities for users to explore.
* Fetch nearby cities with Geonames web services.
* Persist nearby cities in Redis to avoid excessive API calls.
* Updates city details when demographic info changes.
> Feat: Nearby cities search [backend only]

- README.md
- planner/planner.go
- planner/users.go
Developers cannot create new users in `DEVELOPMENT` environment. This change addresses this issue.
* Do not validate user emails in `DEVELOPMENT` environment.
> Fix: developers can create users in DEVELOPMENT env

- iowrappers/redis_client.go
- test/redis_client_mocks/nearby_cities_search_test.go
When Redis clients fail to retrieve city details, the entry in the slice is empty and the client has to filter it out.
* Only pushes valid city details to the result slice.
* Workers send results to a channel for the main Go routine to collect.
> Fix: discard erroneous city retrieval results from Redis

- planner/min_priority_queue.go
- planner/min_priority_queue_vertex_test.go
- planner/solver.go
- planner/vertex.go
Make min priority queue generic. Priority queues in the planner repository should not be limited to holding items of `Vertex` type.
* Define a `PriorityQueueItem` interface and make the `Vertex` type implement it.
* Refactor `MinPriorityQueue` to holding items of generic type of `PriorityQueueItem`.
> Generics: make min priority queue generic

- go.mod
- go.sum
- iowrappers/nearby_search.go
We don't need to obtain places with price level higher than the requested. This reduces the number of places we need to save to the database when querying for lower price levels.
* Simplify search radius adjustment code to use built-in functions.
> Use exact price level in Google Maps search requests

- config/config.yml
We are missing `user_ratings_total` field in Google Maps requests, even though we are using this in calculating scores.
* Add this field in `config/config.yaml`.
> Fix: add user_ratings_total to details search fields list

- config/config.yml
- planner/solver.go
Improve the quality of plan recommendation page, so that the same location may appear in multiple suggested plan trip candidates. Currently, the same place is only allowed to appear once, and this may limit the number of suggested plans for certain cities.
For example, Q pop shop appears twice in the result plan list.
* Add a counter for each place during the main search/solver algorithm
* The counter can be implemented by a hashMap 
* In future PR, we can add this as a configurable param with some refactor on solver.go
> Allow one place to appear multiple times in the search result page

- iowrappers/nearby_search.go
- iowrappers/poi_searcher.go
- iowrappers/redis_client.go
- planner/solver.go
- test/redis_client_mocks/maps_last_search_time_test.go
Previously, we determine if a new API call to the Maps is necessary when the number of results is lower than requested. However, with the new Maps query fixed on min/max price level, this will not work properly since higher priced restaurants are inevitably less than the requested most of the time. Therefore the new logic says as long as we have some data for the location with the requested category and price level, it is acceptable data from the database.
* `MapsSearchTime` entries have `PriceLevel` info now
* Update place freshness if statement
> Update Place freshness logic

- iowrappers/redis_client.go
Currently Google Maps API do not provide pricing info for places such as park, museums, so on. So we can save API calls by ignoring the pricing level in the planning requests.
> Fix: avoid call Google Maps for visit places with different price levels

- iowrappers/data_migrations.go
- iowrappers/data_migrations_test.go
- iowrappers/nearby_search.go
- planner/planner.go
To improve plan quality, we want to remove places with zero user ratings count from the database.
* Add zero user ratings count when cleaning places in Redis.
* Filter places with zero user ratings count when saving places from fresh Maps search results.
> Migrations: User ratings count data migrations

- matching/score.go
- test/score_test.go
This change affects all the places with **Visit** category, since all their current price levels are zero. Previously the place rating to pricing ratios for Visit places are treated flatly, and this affect the result of score since the final score will only depend on the number of user ratings. With this change, the ratings for Visit places will be taken into account.
* Modify the rating-to-pricing ratio to rating divided by the maximum score (5.0).
> Experiement: use a new formula for places price level zero

- iowrappers/poi_searcher.go
- iowrappers/redis_client.go
- iowrappers/utils.go
- matching/matcher.go
- planner/solver.go
Some places in the top results may have broken photo URL. Most of them don't have any user rating count from Google Map API. This is related with issue #310
* Add a filter to remove places with zero user rating count
* Tested locally with debug print messages, do show zero user rating places are gone.
* Plan to follow the matcher style as time and price matchers.
> Add a filter to remove places with zero user rating count

- assets/js/plan_template.js
We used to have a fixed number of pages (5 pages for 10 results) for plan template result section. This is not ideal when the number of results is less than or more than 10 since some pages will show blanks.
* Set pages per planning results received.
> Set number of pages per planning results received

- iowrappers/photos_client.go
- iowrappers/photos_client_test.go
Some place may contain invalid photo URL, such as "www.google.com". see the example of "Birk's". 
Add a new URL validation function, and pass it into URL extraction function.
The new validator checks if the URL starts with a desired prefix. "https://lh3.googleusercontent.com/places/"
- [] Integration testing on Heroku staging
> Add Google photo URL validation

- assets/js/plan_template.js
- planner/solver.go
- test/solution_candidate_selection_test.go
When users query for a large number of time slots (>4) a regular server typically fail to examine all the possible solutions. We could consider collect solutions when computational timeout happen.
* Collect planning solutions when computational timeout happens.
* Move timeout context to `FindBestPlanningSolutions` method since its caller do not need to be aware of this mechanism.
* Remove computational timeout error.
* Increase front-end timeout from 10s to 15s.
> Enhancement: collect planning solutions when timeout happens

- matching/score.go
- matching/score_test.go
- planner/solver.go
Now we are doing early termination when solving combinatorics. So the idea is if the input place lists are sorted by score, the solver would be able to check the places with higher score first, resulting in higher quality plans in general.
* export the function to compute single place score to the higher level packages
* sort places by score before solving the combination problem.
> [Enhancement] Sort places by score before solving combinatorics

- config/config.yml
- iowrappers/photos_client.go
- iowrappers/photos_client_test.go
- main.go
- planner/planner.go
To fix the missing photo issue, we want to experiment using Google maps photo api. Currently the planner uses a native http client that does send some customized request.
* Define a new interface PhotoClient, insert it as a data member in Planner
* Add a flag "enable_maps_photo_client"
* Removed redundant unit tests
> Setup alternative call for planner to use Google maps PhotoClient

- assets/js/plan_template.js
Allow users to view plan details when searching with plan templates.
* Add a `details` button besides each planning result table
> Feat: add plan details for planning results in plan template page

- assets/templates/trip_plan_details_template.html
The plan details page carousel did not consider when we have multiple places in a travel plan. There were 3 fixed button in the HTML page. After users click on the last image, the screen will stuck.
* Render number of carousel buttons per places in the travel plan
* Use dark variant for the carousel indicators
* Reformat the HTML page source code
* Reformat conditional class assignment such as `<div class={{if index $active $i}} "card-body" {{else}} "card-body d-none" {{end}}>` so that we can do the reformat
> Fix: trip details carousel button getting stuck

- iowrappers/maps_client.go
- main.go
- planner/planner.go
- planner/solver.go
- planner/solver_test.go
Remove double init in `solver.go`
* Move the logger initialization to the program entry
* Also rename a few variables for consistency
* Keep the `Logger` in `iowrappers` package since it is for IO purposes.
> Chore: move Zap logger init to main

- planner/planner.go
There is a potential issue that the previous location's place details from one location "leaks" to the next location's place details. For example, the place editorial summary is copied to the next location as users move across the slides.
* The most important fix in this PR is create a new variable for each retrieved place instead of reusing the same one.
```		
var place POI.Place
cacheErr = p.RedisClient.FetchSingleRecord(ctx, placeKey, &place)
go p.asyncGetTripRespPlaceDetails(&wg, &tripResp.PlaceDetails[idx], place)
```
> Fix: get plan details handler function

- assets/js/user_profile.js
- assets/templates/user_profile.html
The number of plans users save may get very large. It looks nice if users can load more plans progressively.
* Set initial number of displayed plans to 3.
* Show load more button when the number of plans is greater than 3.
* Each time user clicks on the load more button, at most 3 more plans are shown.
> Feat: add load more plans button in user profile page

- planner/planner.go
- planner/solver.go
- test/solution_candidate_selection_test.go
Previously the default search radius is 10km, which is quite limited for larger cities. The average radius of the 10 most populated cities in the US is around 18.84 miles.
* Increase default search radius to 20km (~ 12.34 miles) so we consider more places for planning requests.
* Address a TODO item where the computation for best planning results should consider search radius from input instead of using the default.
> Experiment: Update default search radius to 20km

- assets/js/plan_template.js
When removing all the rows in plan templates and adding the first row, the options in start and end time is blank.
* Set default starting hour to be 9AM.
> Fix: adding the first row in plan template does not give hour options

- planner/solver.go
Increase default number of time slots for plans from 3 to 4 since we can handle the extra computational complexity now.
* Add "dinner" time slot from 6PM to 8PM.
* Modify afternoon visit time slot from 1PM to 2PM.
> Increase default number of time slots for plans to 4

- iowrappers/redis_client.go
- iowrappers/users.go
- planner/planner.go
- test/redis_client_mocks/cached_planning_solutions_test.go
Made saving and retrieving planning solutions more robust and less error prone.
* When saving planning solutions, we should first make sure the plan is saved before saving its ID. We are now also cleaning up previous plan IDs if they exist.
* When retrieving planning solutions, we should make sure the plan details are fetched before adding them to the results. Previously we could end up with incomplete results.
> Improve saving and retrieving planning solutions

- iowrappers/redis_client.go
- planner/planner.go
- planner/solver.go
- planner/users.go
When users select higher price levels, the number of candidate places become less. In these cases, the number of available plans are sometimes less than requested. As the same set of candidate places that are used in generating the plans, we are repeatedly generating the same plans over and over again. This is not scalable and wasting computation/storage resources.
* Remove the constraint that the number of saved plans has to be larger than requested.
* `RedisClient.PlanningSolutions` method now returns a pointer instead of a struct.
* Add request ID when users log in.
> Fix: avoid re-generating plans when results are less than requested

- assets/js/google_map.js
- assets/js/place.js
- assets/js/search_results.js
- assets/js/show-trip-details.js
- assets/js/user_profile.js
- iowrappers/redis_client.go
- planner/planner.go
- user/user.go
Related [issue 359](https://github.com/timwangmusic/Vacation-Planner/issues/359). Note that this is a **breaking** change, since users will not be able to check plan details for the previously saved plans.
* Enhance user saved plans to generate the plan details page.
* Set expiration time on system generated plans.
* Save a plan from the result page -> go to details -> save the same plan from there -> verify in the profile that there should be no duplicate
* Save a plan directly from the details page -> go to the result page >  save the same plan from there -> verify in the profile that there should be no duplicate
> Use user saved plan to generate plan details page

- assets/js/google_map.js
- assets/js/google_map.test.js
Add place names as Map marker titles so users can see them while hanging over the markers.
* Set `title` option when constructing markers.
> Add title to markers in Maps

- iowrappers/mailer.go
- iowrappers/redis_client.go
- planner/admins.go
- planner/planner.go
Add an admin endpoint to send announcements to users.
* Only admins can post announcements.
* Announcements are persisted in Redis.
* Concurrently send emails to users.
> Add admin endpoint to send announcement to users

- iowrappers/maps_client.go
Configure production logger level to debug and above since we need more logging in production.
* Use `zap.NewProductionConfig()` and config the logging level instead of `zap.NewProduction()` which limits the logging level at `INFO`.
> Configure production logger level to debug and above

- assets/js/google_map.js
- assets/js/google_map.test.js
The legacy markers for Google Maps is deprecating. In this change we attempt to use the new advanced markers on the mini map.
* Get place categories on the fly and display them with `PinElement`.
* Removed old test cases for legacy markers.
> Feature: Use advanced markers to replace deprecated markers in maps

- assets/css/styles.css
- assets/js/search_results.js
- assets/templates/search_results_layout_template.html
- iowrappers/poi_searcher.go
- iowrappers/redis_client.go
- iowrappers/users.go
- planner/planner.go
- planner/solver.go
- planner/transformers.go
- planner/users.go
- test/redis_client_mocks/cached_planning_solutions_test.go
- test/solution_candidate_selection_test.go
As an effort to increase user interaction with our service and improve personalization, this document discusses how we can implement a [feature](https://github.com/timwangmusic/Vacation-Planner/issues/369) to allow users to thumb up or down thumb up or down a plan.
* Increase maximum cached plans to 100.
* Use sorted set instead of the Redis list for storing plan IDs.
* Copy sorted set of plan IDs for each user who makes the request.
> [Feature]Users like or dislike plans

- iowrappers/jobs.go
- iowrappers/redis_client.go
- main.go
- planner/dispatcher.go
- planner/planner.go
- planner/streaming.go
- planner/utils.go
- planner/workers.go
Previously when a user requests plans that are not generated and stored in the database, the application server computes new plans on the fly. Users will have to wait around 10s to get the results. This is ok for initial queries. When users change any single parameter, such as the price level, they will have to wait since those results are not available even though the only difference is the price level.
In this change, we launch planning solution workers to handle offline jobs. As a start, we enable computing solutions for all the price levels.
* Created a worker dispatcher that runs when the server starts running.
* Created planning solutions workers that handle the async jobs.
* Use Golang's `RWMutex` to guard against concurrent job creations and executions.
> Async jobs for generating planning solutions

- POI/places.go
- assets/js/search_results.js
- iowrappers/poi_searcher.go
- iowrappers/users.go
- planner/planner.go
The goal of this PR is to fix issue #379 . The cause is we relies on URL parameter when posting user plan views. And when using precise location, this parameter appears in the form of latitude and longitude. And this in turn got saved to user plans as travel destinations.
* Use travel destination value from API instead of URL parameter.
* Also disable updating user favorites when using precise location feature.
> Fix precise location display issue in user saved plans

- iowrappers/redis_client.go
- planner/transformers.go
- Weekday transformation function from date in request is wrong. It doesn't compensate for the fact that the `time.Weekday` type starts with Sunday while the internal Weekday starts on Monday.
* Compensate for the difference between `time.Weekday` type and the internal `Weekday` type.
- The Louve Museum closes on Tuesday, currently the planner recommends the museum on Tuesday, which is obviously wrong.
> Fix: weekday value in planning requests

- POI/places.go
- iowrappers/redis_client.go
- planner/solver.go
- planner/transformers.go
- test/redis_client_mocks/cached_planning_solutions_test.go
Plan records do not have time related info. This leads to confusion when front-end needs to post those data in order to have a complete view of the plan.
* Weekdays are saved as their English names in the records.
* Time slots are saved with a format `from x to y`.
```
...
"weekdays":["Saturday","Saturday","Saturday","Saturday"],
"time_slots":["from 10 to 12","from 12 to 13","from 14 to 17","from 18 to 20"]
```
> Persist weekday and time slot info in plan records

- assets/js/search_results.js
- assets/templates/search_results_layout_template.html
- go.mod
- go.sum
- planner/openai.go
- planner/planner.go
- planner/planner_test.go
This is our first AI feature! Generates a plan summary so that users can choose to see plan details in the details pages. This provides an alternative for the tabular view that has served us over the years. Notably we are adding another service! Also another source of cost when deploying to production...
* Integrated OpenAI chat completion API
* Use Bootstrap modal component to display the plan summary UI for minimum search results page UI disruptions.
> Feat: AI generated plan summary

- assets/js/search_results.js
As the functionality for the plan result page increases, we make increasing number of calls to the planning API. Currently there are four types of functionalities make calls to the API endpoint:
* when the page is loaded
* when a user saves a plan
* when a user requests a plan summary
* when a user posts the feedback for a plan
* Store the plans data in a global variable so that all the functionalities can access them once the page is loaded.
> Reduce plans API calls in the search result page

- iowrappers/redis_client.go
- iowrappers/users.go
- planner/planner.go
- planner/streaming.go
- planner/workers.go
Currently the planning API stat uses Redis hyper log, and the values are inaccurate.
* Create hour bucket with UTC time as key.
* Update API call count as request comes in.
> Improve planning API stat collections

- assets/js/search_results.js
The new format show plan summary in bullet points in an unordered list.
* Reformat per description
> Enhancement: improve formatting for plan summary

- assets/js/search_results.js
When users use locations with only city followed by country (e.g. Paris, France), the image is stored under `/` with the current implementation. In this fix, the images will be stored in `country/cities/city_name` directory in the S3 bucket.
* Add a simple validation in the image fetcher.
* Add a fixed filler for location inputs without `admin area one`.
> fix: image location for location input with two parts

- iowrappers/redis_client.go
- planner/planner.go
When plans expire, users will be redirected to the 404 page.
* Directly calling the 404 handler will not render CSS correctly.
> feat: redirect to 404 page when plan details not found

- iowrappers/nearby_search.go
Improve error handling of the core maps search function and remove sleep time between requests to the Maps services.
* Instead of early return when error happens, skip the current place type and wait for the next attempt.
* Remove sleep between requests.
> perf: improve maps nearby search

- assets/js/search_results.js
- assets/templates/search_results_layout_template.html
Add a download button for users to download the location image.
* Since we have S3 signed URL, we just need to add a new download button and assign the same URL to its `download` property. 
* Use material icons.
* Also trying to fix image display issue on smaller devices.
~~[ ] Added new unit tests~~
> feat: add location image download button

- assets/js/search_results.js
- assets/templates/search_results_layout_template.html
Previously, we rely on the mechanism that in order for users to see a set of new plans they have to click on the dislike button. So that the "refresh" will load a new set of travel plans. This change aims to improve the user experience by providing users options to load more plans (up to 15 at the moment). 
-   Pre-fetches 10 extra plans beyond what's displayed for instant "load more"
-   Dynamically renders new plans when clicking "Load More"
-   Button automatically hides when all plans are displayed
-   Scroll-to-top button now fixed position in bottom-right corner
-   Maintains all existing functionality (like/dislike, save, refresh, etc.)
> feat: load more results in the plan results page
